import type { TrackerType } from '@features/trackers/types'

/**
 * Per-type icon sets shown in the form's picker, as ASCII KEYWORDS (not emoji).
 * Icons are persisted as keywords because op-sqlite v16 corrupts non-BMP emoji
 * on write; the emoji glyph is produced for display via `iconEmoji(key)`. Each
 * keyword here must exist in icons.ts ICON_EMOJI and resolve to a distinct
 * glyph within its type.
 *
 * The first 8 of each list are the original curated defaults (they lead the
 * form's 2-row preview); the rest are every icon used by that type's templates,
 * so any template icon is selectable in Create/Edit. A keyword shared across
 * types (e.g. `piggy`) is intentionally the SAME keyword everywhere so the
 * glyph↔keyword reverse map stays consistent.
 */
export const ICONSET: Record<TrackerType, string[]> = {
  habit: [
    'lotus',
    'dumbbell',
    'read',
    'nosmoke',
    'pill',
    'tooth',
    'bed',
    'pray',
    // template icons
    'drop',
    'salad',
    'veggie',
    'apple',
    'coffee',
    'candy',
    'fries',
    'soda',
    'stretch',
    'walk',
    'run',
    'calorie',
    'protein',
    'sneaker',
    'sport',
    'cycle',
    'swim',
    'stand',
    'write',
    'sun',
    'smile',
    'laugh',
    'book',
    'mountain',
    'game',
    'cool',
    'shush',
    'breathe',
    'hand',
    'checkbox',
    'target',
    'notebook',
    'alarm',
    'clock',
    'laptop',
    'phone',
    'tv',
    'star',
    'envelope',
    'tomato',
    'happy',
    'piggy',
    'calendar',
    'bank',
    'receipt',
    'card',
    'institution',
    'plate',
    'takeout',
    'flymoney',
    'cart',
    'globe',
    'memo',
    'think',
    'medal',
    'teacher',
    'brain',
    'bluebook',
    'film',
    'guitar',
    'piano',
    'golf',
    'fishing',
    'blossom',
    'headphone',
    'yarn',
    'thread',
    'artist',
    'hammer',
    'paint',
    'camera',
    'family',
    'woman',
    'man',
    'telephone',
    'speech',
    'loveletter',
    'blush',
    'heart',
    'handshake',
    'speaking',
    'ear',
    'box',
    'basket',
    'broom',
    'sponge',
    'dash',
    'cook',
    'cat',
    'dog',
    'toilet',
    'tree',
    'seedling',
    'car',
    'incomingmail',
    'inbox',
    'raisehand',
    'megaphone'
  ],
  target: [
    'target',
    'book',
    'piggy',
    'scale',
    'run',
    'write',
    'guitar',
    'chart',
    // template icons
    'cash',
    'party',
    'palm',
    'emailarrow',
    'people'
  ],
  average: [
    'drop',
    'sleep',
    'walk',
    'salad',
    'coffee',
    'phone',
    'cash',
    'fire',
    // template icons
    'calorie',
    'protein',
    'raise',
    'sneaker',
    'piggy',
    'flymoney',
    'laptop'
  ],
  project: [
    'rocket',
    'puzzle',
    'build',
    'paint',
    'film',
    'home',
    'work',
    'grad'
  ]
}

/** Default icon keyword for a type when none has been chosen yet. */
export function defaultIcon(type: TrackerType): string {
  return ICONSET[type]?.[0] ?? ICONSET.target[0]
}
